src/Entity/Package.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Collection\PackageCollection;
use App\Collection\VersionCollection;
use App\Entity\Common\AbstractEntity;
use Carbon\Carbon;
use Composer\Package\PackageInterface;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PackageRepository")
 */
class Package extends AbstractEntity
{
    /** @ORM\Column(type="string", options={"default": "vcs"}) */
    private string $type;

    /** @ORM\Column(type="string") */
    private string $url;

    /** @ORM\Column(type="string") */
    private string $name = '';

    /** @ORM\Column(type="boolean", options={"default": true}) */
    private bool $enable = true;

    /** @ORM\Column(type="boolean", options={"default": false}) */
    private bool $abandoned = false;

    /** @ORM\Column(type="string", nullable=true) */
    private ?string $replacementPackage = null;

    /** @ORM\Column(type="text", nullable=true) */
    private ?string $readme = null;

    /** @ORM\Column(type="boolean", options={"default": false}) */
    private bool $autoUpdate = false;

    /** @ORM\Column(type="datetimeutc") */
    private DateTime $lastUpdate;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Version", mappedBy="package", cascade={"persist", "remove"}, orphanRemoval=true)
     *
     * @var Collection<int, Version>
     */
    private Collection $versions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Download", mappedBy="package", cascade={"persist", "remove"}, orphanRemoval=true)
     *
     * @var Collection<int, Download>
     */
    private Collection $downloads;

    private ?VersionCollection $versionsSorted = null;

    private ?PackageCollection $packages = null;

    private ?PackageInterface $lastStable = null;

    public function __construct(
        string $type,
        string $url,
    ) {
        parent::__construct();

        $this->url  = $url;
        $this->type = $type;

        $this->versions   = new ArrayCollection();
        $this->downloads  = new ArrayCollection();
        $this->lastUpdate = Carbon::now();
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): void
    {
        $this->type = $type;
    }

    public function getUrl(): string
    {
        return $this->url;
    }

    public function setUrl(string $url): void
    {
        $this->url = $url;
    }

    public function isEnable(): bool
    {
        return $this->enable;
    }

    public function setEnable(bool $enable): void
    {
        $this->enable = $enable;
    }

    public function isAbandoned(): bool
    {
        return $this->abandoned;
    }

    public function setAbandoned(bool $abandoned): void
    {
        $this->abandoned = $abandoned;
    }

    public function getReplacementPackage(): ?string
    {
        return $this->replacementPackage;
    }

    public function setReplacementPackage(?string $replacementPackage): void
    {
        $this->replacementPackage = $replacementPackage;
    }

    /**
     * @return string[]
     */
    public function getConfig(): array
    {
        return [
            'type' => $this->getType(),
            'url'  => $this->getUrl(),
        ];
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getReadme(): ?string
    {
        return $this->readme;
    }

    public function setReadme(?string $readme): void
    {
        $this->readme = $readme;
    }

    public function isAutoUpdate(): bool
    {
        return $this->autoUpdate;
    }

    public function setAutoUpdate(bool $autoUpdate): void
    {
        $this->autoUpdate = $autoUpdate;
    }

    public function getLastUpdate(): ?DateTime
    {
        return $this->lastUpdate;
    }

    public function setLastUpdate(DateTime $lastUpdate): void
    {
        $this->lastUpdate = $lastUpdate;
    }

    /**
     * @return Collection<int, Download>
     */
    public function getDownloads(): Collection
    {
        return $this->downloads;
    }

    public function getVersions(): VersionCollection
    {
        return VersionCollection::create(...$this->versions->toArray());
    }

    public function getVersionsSorted(): VersionCollection
    {
        if ($this->versionsSorted === null) {
            $this->versionsSorted = $this->getVersions()->sortByReleaseDate();
        }

        return $this->versionsSorted;
    }

    public function getPackages(): PackageCollection
    {
        if ($this->packages === null) {
            $this->packages = $this->getVersionsSorted()->toPackageCollection();
        }

        return $this->packages;
    }

    public function getLastStablePackage(): ?PackageInterface
    {
        if ($this->lastStable === null) {
            $this->lastStable = $this->getPackages()->getLastStablePackage();
        }

        return $this->lastStable;
    }

    public function __toString(): string
    {
        return $this->getName();
    }
}

src/Entity/Version.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Common\AbstractEntity;
use Composer\Package\AliasPackage;
use Composer\Package\Loader\ArrayLoader;
use Composer\Package\PackageInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use function sprintf;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VersionRepository")
 * @ORM\Table(indexes={
 *     @ORM\Index(columns={"package_id", "name"})
 * })
 */
class Version extends AbstractEntity
{
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Package", inversedBy="versions", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private Package $package;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Download", mappedBy="version", cascade={"persist", "remove"}, orphanRemoval=true)
     *
     * @var Collection<int, Download>
     */
    private Collection $downloads;

    /** @ORM\Column(type="string") */
    private string $name;

    /**
     * @ORM\Column(type="json")
     *
     * @var mixed[]
     */
    private array $data = [];

    public function __construct(
        Package $package,
        PackageInterface $composerPackage
    ) {
        parent::__construct();

        $this->package   = $package;
        $this->name      = $composerPackage->getPrettyVersion();
        $this->downloads = new ArrayCollection();
    }

    public function getPackage(): Package
    {
        return $this->package;
    }

    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @return mixed[]
     */
    public function getData(): array
    {
        return $this->data;
    }

    /**
     * @param mixed[] $data
     */
    public function setData(array $data): void
    {
        $this->data = $data;
    }

    public function getPackageInformation(): PackageInterface
    {
        $loader = new ArrayLoader();

        $p = $loader->load($this->getData());

        if ($p instanceof AliasPackage) {
            $p = $p->getAliasOf();
        }

        return $p;
    }

    /**
     * @return Collection<int, Download>
     */
    public function getDownloads(): Collection
    {
        return $this->downloads;
    }

    public function __toString(): string
    {
        return sprintf('%s - %s', $this->getPackage()->getName(), $this->getName());
    }
}

src/Controller/PackageController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Composer\ComposerManager;
use App\Entity\Package;
use App\Form\Type\Forms\PackageAbandonType;
use App\Form\Type\Forms\PackageType;
use App\Form\Validator\PackageValidator;
use App\Service\FlashBagHelper;
use App\Service\PackageSynchronization;
use App\Service\RepositoryHelper;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Psr\Log\LoggerInterface;
use RuntimeException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Callback;
use Throwable;

use function assert;

/**
 * @Route("/packages", name="app_package_")
 */
final class PackageController extends AbstractController
{
    private PackageValidator $packageValidator;

    private ManagerRegistry $registry;

    private PaginatorInterface $paginator;

    private FormFactoryInterface $formFactory;

    private FlashBagHelper $flashBag;

    private ComposerManager $composerManager;

    private RepositoryHelper $repositoryHelper;

    private PackageSynchronization $packageSynchronization;

    private LoggerInterface $logger;

    public function __construct(
        PackageValidator $packageValidator,
        ManagerRegistry $registry,
        PaginatorInterface $paginator,
        FormFactoryInterface $formFactory,
        FlashBagHelper $flashBag,
        ComposerManager $composerManager,
        RepositoryHelper $repositoryHelper,
        PackageSynchronization $packageSynchronization,
        LoggerInterface $logger,
    ) {
        $this->packageValidator       = $packageValidator;
        $this->registry               = $registry;
        $this->paginator              = $paginator;
        $this->formFactory            = $formFactory;
        $this->flashBag               = $flashBag;
        $this->composerManager        = $composerManager;
        $this->repositoryHelper       = $repositoryHelper;
        $this->packageSynchronization = $packageSynchronization;
        $this->logger                 = $logger;
    }

    /**
     * @Route("", name="index")
     */
    public function index(Request $request): Response
    {
        $repository = $this->registry->getRepository(Package::class);
        $qb         = $repository->createQueryBuilder('p');

        $page = $request->query->getInt('page', 1);

        $sort      = $request->query->get('sort', 'p.name');
        $direction = $request->query->get('direction', 'asc');
        $filter    = $request->query->get('filter');

        $qb->orderBy($sort, $direction);

        if ($filter !== null) {
            $qb->orWhere($qb->expr()->like('p.name', ':filter'));
            $qb->orWhere($qb->expr()->like('p.readme', ':filter'));
            $qb->orWhere($qb->expr()->like('p.url', ':filter'));
            $qb->orWhere($qb->expr()->like('p.replacementPackage', ':filter'));
            $qb->setParameter('filter', '%' . $filter . '%');
        }

        $pagination = $this->paginator->paginate($qb, $page);

        return $this->render('package/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }

    /**
     * @Route("/{package}/abandon", name="abandon")
     */
    public function abandon(Request $request, Package $package): Response
    {
        $form = $this->formFactory->create(PackageAbandonType::class, $package);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->registry->getManager();

            $package->setAbandoned(true);
            $em->persist($package);
            $em->flush();

            $this->flashBag->success('Package abandoned');

            return $this->redirectToRoute('app_package_index');
        }

        return $this->render('package/abandon.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{package}/unabandon", name="unabandon")
     */
    public function unabandon(Request $request, Package $package): Response
    {
        $em = $this->registry->getManager();

        $package->setAbandoned(false);
        $package->setReplacementPackage(null);

        $em->persist($package);
        $em->flush();

        $this->flashBag->success('Package unabandoned');

        if ($request->headers->get('referer') !== null) {
            $referer = $request->headers->get('referer');

            return $this->redirect($referer);
        }

        return $this->redirectToRoute('app_package_index');
    }

    /**
     * @Route("/{package}/enable", name="enable")
     */
    public function enable(Request $request, Package $package): Response
    {
        $em = $this->registry->getManager();

        $package->setEnable(true);

        $em->persist($package);
        $em->flush();

        if ($request->headers->get('referer') !== null) {
            $referer = $request->headers->get('referer');

            return $this->redirect($referer);
        }

        return $this->redirectToRoute('app_package_index');
    }

    /**
     * @Route("/{package}/disable", name="disable")
     */
    public function disable(Request $request, Package $package): Response
    {
        $em = $this->registry->getManager();

        $package->setEnable(false);

        $em->persist($package);
        $em->flush();

        if ($request->headers->get('referer') !== null) {
            $referer = $request->headers->get('referer');

            return $this->redirect($referer);
        }

        return $this->redirectToRoute('app_package_index');
    }

    /**
     * @Route("/add", name="add")
     */
    public function add(Request $request): Response
    {
        $form = $this->createForm(PackageType::class, null, [
            'constraints' => [
                new Callback([
                    $this->packageValidator,
                    'validateRepository',
                ]),
                new Callback([
                    $this->packageValidator,
                    'validateAddName',
                ]),
            ],
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $package = $form->getData();
            assert($package instanceof Package);

            try {
                $repository = $this->composerManager->createRepository($package);
                $info       = $this->repositoryHelper->getComposerInformation($repository);

                if (! isset($info['name'])) {
                    throw new RuntimeException('name is missing', 1608916971650);
                }

                $package->setName($info['name']);

                $this->packageSynchronization->sync($package);

                $this->flashBag->success('Package added');
            } catch (Throwable $exception) {
                $this->flashBag->alert('Could not add package. Please try it again');

                $this->logger->error('Could not add package', [
                    'exception' => $exception,
                ]);

                return $this->render('package/add.html.twig', [
                    'form' => $form->createView(),
                ]);
            }

            return $this->redirectToRoute('app_package_index');
        }

        return $this->render('package/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{package}/edit", name="edit")
     */
    public function edit(Request $request, Package $package): Response
    {
        $form = $this->createForm(PackageType::class, $package, [
            'constraints' => [
                new Callback([
                    $this->packageValidator,
                    'validateRepository',
                ]),
                new Callback([
                    'callback' => [
                        $this->packageValidator,
                        'validateEditName',
                    ],
                    'payload'  => $package,
                ]),
            ],
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $package->setAutoUpdate(false);

                $this->packageSynchronization->sync($package);

                $this->flashBag->add('success', 'Package updated');
            } catch (Throwable $exception) {
                $this->flashBag->alert('Could not update package. Please try it again');

                $this->logger->error('Could not update package', [
                    'exception' => $exception,
                ]);

                return $this->render('package/edit.html.twig', [
                    'form'    => $form->createView(),
                    'package' => $package,
                ]);
            }

            return $this->redirectToRoute('app_package_edit', [
                'package' => $package->getId(),
            ]);
        }

        return $this->render('package/edit.html.twig', [
            'form'    => $form->createView(),
            'package' => $package,
        ]);
    }

    /**
     * @Route("/{package}/delete", name="delete")
     */
    public function delete(Package $package): Response
    {
        $em = $this->registry->getManager();

        $em->remove($package);
        $em->flush();

        $this->flashBag->add('success', 'Package removed');

        return $this->redirectToRoute('app_package_index');
    }

    /**
     * @Route("/{package}/update", name="update")
     */
    public function update(Request $request, Package $package): Response
    {
        try {
            $this->packageSynchronization->sync($package);

            $this->flashBag->add('success', 'Package updated');
        } catch (Throwable $exception) {

src/Resources/views/package/abandon.html.twig
{% extends '@Devliver/layout.html.twig' %}

{% block pageTitle %}
    <i class="fas fa-archive fa-fw"></i> {{ 'package.abandon.page_header'|trans }}
{% endblock %}

{% block pageActions %}
    <a href="{{ path('devliver_package_index') }}" data-title="{{ 'action.cancel'|trans }}" class="btn btn-outline-danger bs-tooltip"><span class="fas fa-ban fa-fw"></span> {{ 'action.cancel'|trans }}</a>
{% endblock %}

{% block content %}
    <div class="alert alert-info">
        You are about to mark this package as abandoned. This will alert users that this package will no longer be maintained.<br><br>
        If you are handing this project over to a new maintainer or know of a package that replaces it, please use the field below to point users to the new package.<br>
        In case you cannot point them to a new package, this one will be tagged as abandoned without a package that replace it.
    </div>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

src/Resources/views/package/add.html.twig
{% extends '@Devliver/layout.html.twig' %}

{% block pageTitle %}
    <i class="fas fa-plus fa-fw"></i> {{ 'package.add.page_header'|trans }}
{% endblock %}

{% block pageActions %}
    <a href="{{ path('devliver_package_index') }}" data-title="{{ 'action.cancel'|trans }}" class="btn btn-outline-danger bs-tooltip"><span class="fas fa-ban fa-fw"></span> {{ 'action.cancel'|trans }}</a>
{% endblock %}

{% block content %}
    {{ form_start(form) }}

    {{ form_widget(form) }}

    {{ form_end(form) }}
{% endblock %}

src/Resources/views/package/edit.html.twig
{% extends '@Devliver/package/add.html.twig' %}

{% block pageTitle %}
    <i class="fas fa-edit fa-fw"></i> {{ 'package.edit.page_header'|trans }}
{% endblock %}

{% block pageActions %}
    <a href="{{ path('devliver_package_add') }}" data-title="{{ 'action.add'|trans }}" class="btn btn-primary bs-tooltip"><span class="fas fa-plus fa-fw"></span> {{ 'action.add'|trans }}</a>
    {{ parent() }}
{% endblock %}

src/Resources/views/package/list.html.twig
{% extends '@Devliver/layout.html.twig' %}

{% block pageTitle %}
    <i class="fas fa-cube fa-fw"></i> {{ 'package.list.page_header'|trans }}
{% endblock %}

{% block pageActions %}
    <a class="btn btn-outline-primary bs-confirmation" href="{{ path('devliver_package_update_all') }}" data-confirmation="Do you really want to update all repositories? This can take a long time."><span class="fas fa-sync fa-fw"></span> {{ 'action.update_all'|trans }}</a>
    <a class="btn btn-primary" href="{{ path('devliver_package_add') }}"><span class="fas fa-plus fa-fw"></span> {{ 'package.add_package'|trans }}</a>
{% endblock %}

{% block content %}
    <div class="row mb-3">
        <div class="col-md-8">
            {{ knp_pagination_render(pagination) }}
        </div>
        <div class="col-md-4">
            <form method="get">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupPrepend"><i class="fas fa-search"></i></span>
                    </div>
                    <input type="text" name="filter" value="{{ app.request.query.get('filter') }}" class="form-control" placeholder="Filter">
                    <div class="input-group-append">
                        <button class="btn btn-outline-primary" type="submit"><i class="fas fa-search fa-fw"></i> Search</button>
                        <a href="{{ path(app.request.get('_route')) }}" class="btn btn-outline-danger"><i class="fas fa-undo fa-fw"></i> Reset</a>
                    </div>

                </div>
            </form>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Packages <span class="badge badge-primary">{{ pagination.getTotalItemCount }}</span>
                </div>
                <div class="card-body p-0">
                    <table class="table table-striped table-hover mb-0">

                        <tr>
                            <th>{{ knp_pagination_sortable(pagination, '#', ['p.id']) }}</th>
                            <th>{{ knp_pagination_sortable(pagination, 'Name', ['p.name']) }}</th>
                            <th>Last Version</th>
                            <th>Datum</th>
                            <th>Last Update</th>
                            <th></th>
                            <th></th>
                        </tr>
                        {% set counter = (pagination.getCurrentPageNumber - 1) * pagination.getItemNumberPerPage %}
                        {% for package in pagination %}
                            {% set counter = counter + 1 %}
                            <tr class="">
                                <td style="white-space: nowrap; width: 1px;">{{ counter }}</td>
                                <td>
                                    <a href="{{ path('devliver_package_view', {package: package.id}) }}" style="font-weight: bold;">
                                        {{ package.name }}
                                    </a>

                                    {% if package.enable == false %}
                                        <span class="badge badge-danger">Disabled</span>
                                    {% endif %}

                                    {% if package.abandoned %}
                                        <span class="badge badge-warning">Abandoned</span>
                                    {% endif %}

                                    <br>
                                    <a href="{{ path('devliver_package_view', {package: package.id}) }}">
                                        {{ package.url }}
                                    </a><br>
                                    {{ package.lastStablePackage.description }}
                                </td>
                                <td>
                                    {{ package.lastStablePackage.prettyVersion }}
                                </td>
                                <td>
                                    {{ package.lastStablePackage.releaseDate|date }}
                                </td>
                                <td>
                                    {{ package.lastUpdate|date }}
                                </td>
                                <td>
                                    <span class="badge badge-primary">Downloads: {{ package_downloads(package)|number_format }}</span><br>
                                    {% if package.autoUpdate %}
                                        <span class="badge badge-success">Auto Update</span><br>
                                    {% else %}
                                        <span class="badge badge-danger">No Auto Update</span><br>
                                    {% endif %}
                                </td>
                                <td style="white-space: nowrap; width: 1px;">
                                    <div class="btn-group">
                                        {% if package.enable != true %}
                                            <a href="{{ path('devliver_package_enable', { package: package.id }) }}" data-title="{{ 'action.enable'|trans }}" class="bs-tooltip btn btn-xs btn-danger"><span class="fas fa-circle fa-fw"></span></a>
                                        {% else %}
                                            <a href="{{ path('devliver_package_disable', { package: package.id }) }}" data-title="{{ 'action.disable'|trans }}" class="bs-tooltip btn btn-xs btn-success"><span class="fas fa-circle fa-fw"></span></a>
                                        {% endif %}
                                        <a href="{{ path('devliver_package_edit', { package: package.id }) }}" data-title="{{ 'action.edit'|trans }}" class="bs-tooltip btn btn-xs btn-primary"><span class="fas fa-edit fa-fw"></span></a>
                                        <a href="{{ path('devliver_package_update', { package: package.id, referer: true }) }}" data-title="{{ 'action.update'|trans }}" class="bs-tooltip btn btn-xs btn-info"><span class="fas fa-sync fa-fw"></span></a>
                                        <a href="{{ path('devliver_package_delete', { package: package.id }) }}" data-confirmation="Remove?" data-title="{{ 'action.remove'|trans }}" class="btn btn-xs bs-confirmation bs-tooltip btn-danger"><span class="fas fa-trash fa-fw"></span></a>

                                        {% if package.abandoned != true %}
                                            <a href="{{ path('devliver_package_abandon', { package: package.id }) }}" data-title="{{ 'action.abandon'|trans }}" class="bs-tooltip btn btn-xs btn-warning"><span class="fas fa-archive fa-fw"></span></a>
                                        {% else %}
                                            <a href="{{ path('devliver_package_unabandon', { package: package.id }) }}" data-title="{{ 'action.unabandon'|trans }}" class="bs-tooltip btn btn-xs btn-dark"><span class="fas fa-archive fa-fw"></span></a>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            {{ knp_pagination_render(pagination) }}
        </div>
        <div class="col-md-6 text-right">
            {{ block('pageActionsGroup') }}
        </div>
    </div>
{% endblock %}