src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Domain\Role;
use App\Entity\Common\AbstractEntity;
use Doctrine\ORM\Mapping as ORM;
use InvalidArgumentException;
use Symfony\Component\Security\Core\User\UserInterface;

use function array_search;
use function array_unique;
use function implode;
use function in_array;
use function sprintf;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User extends AbstractEntity implements UserInterface
{
    /** @ORM\Column(type="string") */
    private string $email;

    /** @ORM\Column(type="string", nullable=true) */
    private ?string $password = null;

    /** @ORM\Column(type="boolean", options={"default": true}) */
    private bool $enable = true;

    /**
     * @ORM\Column(type="json")
     *
     * @var string[]
     */
    private array $roles = [];

    public function __construct(
        string $email
    ) {
        parent::__construct();

        $this->email = $email;
    }

    public function getUsername(): string
    {
        return $this->getEmail();
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): void
    {
        $this->password = $password;
    }

    public function isEnable(): bool
    {
        return $this->enable;
    }

    public function setEnable(bool $enable): self
    {
        $this->enable = $enable;

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function addRole(string | Role $role): void
    {
        $role = (string) $role;

        if (in_array($role, $this->roles, true)) {
            return;
        }

        if (! Role::isValid($role)) {
            throw new InvalidArgumentException(sprintf('%s given but $role has to be one of these values: %s', $role, implode(', ', Role::toArray())));
        }

        $this->roles[] = $role;
    }

    public function removeRole(string | Role $role): void
    {
        $role = (string) $role;

        if (! in_array($role, $this->roles, true)) {
            return;
        }

        unset($this->roles[array_search($role, $this->roles, true)]);
    }

    public function getSalt(): ?string
    {
        return null;
    }

    public function eraseCredentials(): void
    {
    }
}

src/Resources/views/security/login.html.twig
{% extends '@Devliver/layout.html.twig' %}

{% trans_default_domain 'FOSUserBundle' %}

{% block pageTitle %}
    <i class="fas fa-sign-in-alt fa-fw"></i> {{ 'security.login.page_header'|trans({}, 'messages') }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}

    <link rel="stylesheet" href="{{ asset('bundles/devliver/css/signin.css') }}">
{% endblock %}

{% block content %}
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    <div class="row">
        <div class="col-md-4">
            <form action="{{ path("fos_user_security_check") }}" class="form-signin" method="post">
                {% if csrf_token %}
                    <input type="hidden" name="_csrf_token" value="{{ csrf_token }}"/>
                {% endif %}

                <label for="_username" class="sr-only">{{ 'security.login.username'|trans }}</label>
                <input type="text" id="_username" name="_username" class="form-control" value="{{ last_username }}" placeholder="{{ 'security.login.username'|trans }}" required autofocus>

                <label for="_password" class="sr-only">{{ 'security.login.password'|trans }}</label>
                <input type="password" id="_password" name="_password" class="form-control" placeholder="{{ 'security.login.password'|trans }}" required>

                <div class="custom-control mb-3 custom-checkbox">
                    <input type="checkbox" name="_remember_me" value="on" class="custom-control-input" id="_remember_me">
                    <label class="custom-control-label" for="_remember_me">{{ 'security.login.remember_me'|trans }}</label>
                </div>

                <button class="btn btn-primary btn-block" type="submit" id="_submit" name="_submit">
                    <i class="fas fa-sign-in-alt fa-fw"></i> {{ 'security.login.submit'|trans }}
                </button>

                <p class="mt-3">
                    <a href="{{ path("fos_user_resetting_request") }}">Passwort vergessen</a>
                </p>
            </form>
        </div>
    </div>

{% endblock %}